### ISSUE TITLE
There is no package version for 2018.3+

### ISSUE THREAD

**Issue by qrokodial** [Unity-Technologies/2d-extras#123]
Seems like the `package` branch was changed to match the 2019 API and no longer works with 2018.4 LTS.

Use of the `package` branch on Unity 2018.4 now results in the following error:

`Packages\com.unity.2d.tilemap.extras\Editor\Tiles\RuleTile\CustomRuleTileMenu.cs(8,31): error CS0117: 'ProjectWindowUtil' does not contain a definition for 'CreateScriptAssetFromTemplateFile'`

**Comment by ChuanXin-Unity** [comment]
Hi, sorry about this!

The package branch has been updated with a fix for this:
https://github.com/Unity-Technologies/2d-extras/commit/d4d5c3720142af52b3a753cd3ba19258672a87e1
