### ISSUE TITLE
Does this work for Unity 2019.2 ?

### ISSUE THREAD

**Issue by cloakedninjas** [Unity-Technologies/2d-extras#103]
Am I doing something wrong, I assume I just drag the folder into my assets ? When I do I get a bunch of errors:

```
Assets\2d-extras-master\2d-extras-master\Assets\Tilemap\Brushes\Prefab Brush\Scripts\Editor\PrefabBrush.cs(10,32): error CS0246: The type or namespace name 'GridBrush' could not be found (are you missing a using directive or an assembly reference?)
```

```
Assets\2d-extras-master\2d-extras-master\Assets\Tilemap\Brushes\Coordinate Brush\Scripts\Editor\CoordinateBrush.cs(39,42): error CS0246: The type or namespace name 'GridBrushEditor' could not be found (are you missing a using directive or an assembly reference?)
```

**Comment by md-one** [comment]
it is the same problem with me and i tried to change to multiple version and now my hole project is a mess and buggy

**Comment by Globfishy** [comment]
I have the exact same issue as well. It is sort of preventing me from working on my game at the moment so a fix would be much appreciated

**Comment by Globfishy** [comment]
First of all, I’m just going to say that I am no expert at this but I did however find a way to make the errors go away. Since the problem seems to exist within the brushes, I simply deleted that folder. If you, like me, only need the rule tiles, this could be a temporary solution

**Comment by Seanba** [comment]
It looks like `GridBrush` (and `GridBrushBase`) were moved to the `UnityEditor.Tilemaps` namespace with Unity 2019.2+.

I suspect this will be fixed soonish but in the meantime I added `using UnityEditor.Tilemaps;` to each file that was failing to compile.

**Comment by ChuanXin-Unity** [comment]
Currently, master will not work with 2019.2 as it targets 2019.1, the current official release. 

You will need to use the package/2019.2 branch to handle the changes made in 2019.2 with the Tilemap Editor package. Please follow the instructions in the README there on how to setup 2d-extras.

**Comment by cianiandreadev** [comment]
Sorry @ChuanXin-Unity I am still the same issue.

Should I try to use the `package_2019.2`? I don't get how this should solve the issue, there are no differences between the master and that branch. Am I doing something wrong?

<img width="1045" alt="Screenshot 2019-08-15 at 16 31 17" src="https://user-images.githubusercontent.com/1215511/63101816-22aa1d00-bf7a-11e9-9a34-3ba19e7f29a4.png">

**Comment by ChuanXin-Unity** [comment]
@cianiandreadev  

No, you are not doing anything wrong. I moved `package_2019.2` to `master` as Unity 2019.2 is currently now the latest official version.

Do you still get this error when using `master` with Unity 2019.2 and the 2D Tilemap Editor package?

**Comment by cianiandreadev** [comment]
Thanks for the anwser @ChuanXin-Unity.
Yes, I still had issues and I had to modify the manifest.
Once modified the manifest pointing to the 2019.2 branch (or master) it works.
But It didn't work out of the box after updating the project from 2019.1 to 2019.2

**Comment by ChuanXin-Unity** [comment]
> But It didn't work out of the box after updating the project from 2019.1 to 2019.2

Would it be possible to share the problems you had updating your project from 2019.1 to 2019.2? We'll try to improve this. Thanks!

**Comment by cianiandreadev** [comment]
@ChuanXin-Unity 
[Note: When I tried to migrate the 2019.2 was already officially released].
I had the error reported above by @cloakedninjas.
Then, googling around I found this issue (and other still commented by you but I think in the Unity forum) and I followed your advice about modifying the manifest.
I then followed the pattern...
`"PackageName": "https://YourGitHost.com/UserName/RepoName.git#BranchName",`
to change from the previous 2D-Extras package to the one pointing to this repository (and the 2019.2 branch, even if, as I previously pointed out, the master and 2019.2 branches are the same).
After that other issues like the missing Sprite Editor (removed in 2019.2 ??) and some warnings.
But in the end the project seems now alive :)

**Comment by ChuanXin-Unity** [comment]
I guess there were some problems while including the 2D packages when upgrading from 2019.1 to 2019.2. When upgrading from 2019.1 to 2019.2, the Unity Package Manager will try to add the 2D Tilemap Editor and the 2D Sprite package (for the Sprite Editor) to your project. It seems that did not happen correctly for you (and other users!). 

To fix this, you can manually add these missing packages using the Unity Package Manager under Windows/Package Manager in Unity. This should make the Tilemap Extras from master work as well.

Let me know if that helps (if you happen to need to upgrade more projects from 2019.1 to 2019.2)!

**Comment by cianiandreadev** [comment]
@ChuanXin-Unity Thanks for your answer. Yes, I already did that and currently my project seems to work correctly under Unity 2019.2.
I was just trying to explain you the issues I had. :)

**Comment by cianiandreadev** [comment]
Currently I only have 1 active projects that needed this kind of update. But I am quite sure this info will be useful to other users as well :)
Thank you very much

**Comment by gl33mer** [comment]
@ChuanXin-Unity  Hi. I've been following this thread. I have a different set of errors when importing 2d-extras into a 2019.2 project (it's the unity robodash - vanilla - fixed for 2019.2 - added the using statements and the package necessary. no errors. all is well).
When 2d-extras is imported I receive these errors:

`Assets\Scripts\Editor\TintTextureGeneratorEditor.cs(9,26): error CS0433: The type 'TintTextureGenerator' exists in both 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'Unity.2D.Tilemap.Extras, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
Assets\Scripts\Editor\GridInformationEditor.cs(11,26): error CS0433: The type 'GridInformation' exists in both 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'Unity.2D.Tilemap.Extras, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
`

There's one more similar one.

To make clear, I'm importing the package with the added line in the manifest file and using the master branch.

**Comment by ChuanXin-Unity** [comment]
@gl33mer 

> Assets\Scripts\Editor\TintTextureGeneratorEditor.cs
> Assets\Scripts\Editor\GridInformationEditor.cs

Theses files are duplicates from the 2d-extras package. You can remove them from the Assets folder to resolve the error.

If the last case has the same error message, you can try to remove the duplicate file too.

**Comment by gl33mer** [comment]
@ChuanXin-Unity 
Thank you for the quick response.

It seems the new TintTextureGenerator has a different api than the original (the one in the Assets folder) - for example. Refresh() instead of RefreshTint(), etc. with different params.

**Comment by thomasyi79** [comment]
Hello, I'm new to this and I'm just following an Udemy course for creating a game like Dungeon Escape. I can't seem to find the asset folder for this project? I went to the url given by the course:  https://github.com/unity-technologies/2d-extras
and I couldn't find the assets folder that I need to download for the sake of the Udemy course. Any help?

**Comment by ChuanXin-Unity** [comment]
@thomasyi79 
Hi, I am not sure which version of Unity you are using or the version of Unity the Udemy course is referring to. If you could share that, that would be helpful!

In the meantime, you could try this URL: https://github.com/Unity-Technologies/2d-extras/tree/2018.3. This should have the 2d-extras set up with the Assets which I believe the Udemy course is referring to.

If you are using the latest version of Unity (or at least 2019.2), you will need to follow the usage guide found in the README of https://github.com/unity-technologies/2d-extras. Hopefully the Udemy course will not be diverted that much due to this!
