### ISSUE TITLE
Update from Unity 2019.1 to 2019.2

### ISSUE THREAD

**Issue by GieziJo** [Unity-Technologies/2d-extras#122]
I'm trying to update my project from Unity 2019.1 to 2019.2, but I am facing an issue.

In unity 2019.1 I installed the package the old way, by download the package and installing it.
The problem is that when updating to 2019.2, the package has been added to the package manager.
This seems to cause compatibility issues, generating errors of the like:
`error CS0115: 'TintBrushSmoothEditor.OnPaintInspectorGUI()': no suitable method found to override` and `error CS0246: The type or namespace name 'GridBrushEditorBase' could not be found (are you missing a using directive or an assembly reference?)` (there are 38 errors).

I am assuming this is because of an updating error, but I am not sure.

Is there a safe way to update the project which I am not aware of?

I tried to look around but did not find related issues.

**Comment by GieziJo** [comment]
I just found the update [guide](https://docs.google.com/document/d/1UvteXCAFL1vZgd6cZBadYI0OC8PHIApO0JuQyi1AtDg/preview), not sure how I missed that before, sorry.

But I am stuck at the "If you are referencing the Tilemap Tooling classes with scripts which are part of an Assembly Definition, you will need to add the “Unity.2D.Tilemap.Editor” Assembly Definition as an Assembly Definition Reference under your Assembly Definition" part.

Where can I find my Assembly Definition?

Thanks

**Comment by ChuanXin-Unity** [comment]
Hi,

> This seems to cause compatibility issues, generating errors of the like:
> `error CS0115: 'TintBrushSmoothEditor.OnPaintInspectorGUI()': no suitable method found to override` and `error CS0246: The type or namespace name 'GridBrushEditorBase' could not be found (are you missing a using directive or an assembly reference?)` (there are 38 errors).

This can be fixed by importing the "2D Tilemap Editor" package from the Unity Package Manager. However, the Tilemap Extras package set up here should have had that as a dependency and imported the "2D Tilemap Editor" package automatically for you. I will check it out and see if there are issues around this when upgrading. In the meantime, you could import the "2D Tilemap Editor" package manually.

> But I am stuck at the "If you are referencing the Tilemap Tooling classes with scripts which are part of an Assembly Definition, you will need to add the “Unity.2D.Tilemap.Editor” Assembly Definition as an Assembly Definition Reference under your Assembly Definition" part.

This would depend on whether you are using [Assembly Definition](https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html) assets inside your project.  These are used mainly for reducing compilation time for your project. If you have them in the project (they have the .asmdef extension) and the scripts there refer to , you can select the asset in your project folder and add the "Unity.2D.Tilemap.Editor" assembly definition under the assembly definition references section. If you do not have them in your project, then you do not need to do anything for this step.

Hope this helps!

**Comment by GieziJo** [comment]
Thanks for your awnser.

> This can be fixed by importing the "2D Tilemap Editor" package from the Unity Package Manager. However, the Tilemap Extras package set up here should have had that as a dependency and imported the "2D Tilemap Editor" package automatically for you. I will check it out and see if there are issues around this when upgrading. In the meantime, you could import the "2D Tilemap Editor" package manually.

The "2D Tilemap Editor" was indeed automatically imported on updating.

> This would depend on whether you are using [Assembly Definition](https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html) assets inside your project. These are used mainly for reducing compilation time for your project. If you have them in the project (they have the .asmdef extension) and the scripts there refer to , you can select the asset in your project folder and add the "Unity.2D.Tilemap.Editor" assembly definition under the assembly definition references section. If you do not have them in your project, then you do not need to do anything for this step.

I do not myself, but by searching through the hierarchy I found that multiple packages activated through the package manager do.

By paying a bit more attention to the errors I can say that much.
The errors are all related to brushes, and are all in the folder `Plugins/Tilemap/Bruches`, and there are 3 errors per brush. For example for Tint Brush Smooth:
- Assets\Plugins\Tilemap\Brushes\Tint Brush Smooth\Scripts\Editor\TintBrushSmooth.cs(87,39): error CS0246: The type or namespace name 'GridBrushEditorBase' could not be found (are you missing a using directive or an assembly reference?)
- Assets\Plugins\Tilemap\Brushes\Tint Brush Smooth\Scripts\Editor\TintBrushSmooth.cs(91,32): error CS0115: 'TintBrushSmoothEditor.validTargets': no suitable method found to override
- Assets\Plugins\Tilemap\Brushes\Tint Brush Smooth\Scripts\Editor\TintBrushSmooth.cs(99,24): error CS0115: 'TintBrushSmoothEditor.OnPaintInspectorGUI()': no suitable method found to override

And so forth for all brushes.
Maybe I just need to delete these folders?
But I think this will break my custom brushes which depend on these scripts.

**Comment by GieziJo** [comment]
So I think I've solved it.

I noticed that all brushes derive from `GridBrush` and `GridBrushBase`. Looking for errors related to that, I stumbled upon the [solution that you provided](https://forum.unity.com/threads/unity-2019-2-0-alpha-7-gridbrush-error.639139/).
I then added `using UnityEditor.Tilemaps;` to all the brushes in the plugin which were derived from the two classes, and it now seems to work.

I guess there this should probably happen during the upgrade, and I don't understand why the brushes in the plugin folder are not in the package folder (they are not my brushes, they are the plugin brushes).

But it works for me know.
Thanks for your help :)
